services:
  - type: web
    name: ai-persona-webapp
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    workingDirectory: backend
    envVars:
      - key: FLASK_ENV
        value: production
